spring.application.name=enterprise-pm-suite

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/enterprise_pm_suite
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

server.tomcat.basedir=D:/projects/enterprise-temp

jwt.secret=mySuperSecretKeyForJwtAuthentication123456789
jwt.expiration=86400000

